🔀 ::(#98) HealthKitTask 설정
Walkhub/Walkhub pull request #101
Opened 2022-01-19 12:40 UTC by rlarldud1234

## 개요
> HealthKitTask 설정 및 테스트

## 작업사항
- HealthKitTask

2022-01-20 03:00 UTC, kimxwan0319 approved these changes

2022-01-20 03:00 UTC, kimxwan0319 requested changes

2022-01-20 03:00 UTC, kimxwan0319 commented on Service/Sources/Data/LocalDataSource/HealthKit/HealthKitTask.swift
> +@available(iOS 14.5, *)
요거 지워주세요.

2022-01-20 03:16 UTC, rlarldud1234 commented on Service/Sources/Data/LocalDataSource/HealthKit/HealthKitTask.swift
> +@available(iOS 14.5, *)
했습니다

2022-01-20 06:50 UTC, kimxwan0319 approved these changes

2022-01-21 00:27 UTC, kimxwan0319 commented
#105 닫히기 전까지 보류합니다. 이후에 수정 필요합니다.

2022-01-25 06:45 UTC, kimxwan0319 requested changes

2022-01-25 06:45 UTC, kimxwan0319 commented on Service/Sources/Data/LocalDataSource/HealthKit/HealthKitDataSource.swift
> +import RxSwift
foundation과 RxSwift 사이에 한칸 띄어주세요.

2022-01-25 07:10 UTC, kimxwan0319 approved these changes

2022-01-25 07:12 UTC, kimxwan0319 requested changes

2022-01-25 07:12 UTC, kimxwan0319 commented on Service/Sources/Data/LocalDataSource/HealthKit/HealthKitDataSource.swift
> +
```swift
final class HealthKitDataSource {

static let shared = HealthKitDataSource()

private init()
```
으로 싱글톤 객체로 변경해주세요.

2022-01-25 13:59 UTC, kimxwan0319 commented on Service/Sources/Data/LocalDataSource/HealthKit/HealthKitDataSource.swift
> +
@rlarldud1234 class 앞에 final 붙여주세요.

2022-01-26 02:49 UTC, kimxwan0319 approved these changes

2022-01-26 10:45 UTC, merged