🔀::(#63) UserRankDTO & SchoolRankDTO
Walkhub/Walkhub pull request #74
Opened 2022-01-13 07:45 UTC by rlarldud1234

## 개요
> 유저&학교 검색시 나오는 목록과 정보 DTO

## 작업사항
- UserRankDTO
- UserListDTO
- SchoolRankDTO
- SchoolDTO

2022-01-13 13:04 UTC, kimxwan0319 requested changes
List가 붙은 struct 네이밍만 수정해주세요.

2022-01-13 13:04 UTC, kimxwan0319 commented on Service/Sources/Data/RemoteDataSource/DataMapping/UserRankDTO.swift
> +    struct RankList: Decodable {
Rank로 변경 필요합니다.

2022-01-13 13:04 UTC, kimxwan0319 commented on Service/Sources/Data/RemoteDataSource/DataMapping/SchoolRankDTO.swift
> +    struct SchoolList: Decodable {
School로 변경 필요합니다.

2022-01-13 14:09 UTC, kimxwan0319 commented
API 수정되었습니다. 확인후 수정부탁드립니다.
User와 School 정보가 통일 된텐데 따로 DTO로 빼서 재사용하시면 좋습니다.

2022-01-14 02:06 UTC, rlarldud1234 commented
@kimxwan0319 다 했습니다.

2022-01-14 03:06 UTC, kimxwan0319 approved these changes
LGTM 👍👍

2022-01-14 07:17 UTC, merged